version: '3.9'

volumes:
  postgres_data:

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: sifonyan/yamdb_final:latest
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/django/static:ro
      - ./media:/var/www/django/media:ro
    depends_on:
      - web
    ports:
      - 80:80
